import { Controller, Get, Param, Res } from '@nestjs/common';
import { Response } from 'express';

@Controller('api/files')
export class FilesController {
  @Get('mock/:filename')
  getMockFile(@Param('filename') filename: string, @Res() res: Response) {
    // Generate a simple dummy buffer for mock downloads
    const buffer = Buffer.from(
      `This is a mock downloaded file for: ${filename}\n\nGenerated by OTS Web Portal API.`,
      'utf-8',
    );

    res.set({
      'Content-Type': 'application/octet-stream',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': buffer.length.toString(),
    });

    res.send(buffer);
  }
}
